# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
envFrom: []
ports: []
# - name: http
#   containerPort: 80
#   protocol: TCP

# livenessProbe:
#   enabled: false
#   path: /
#   port: http
# readinessProbe:
#   enabled: false
#   path: /
#   port: http

# strategy:
#   rollingUpdate:
#     maxSurge: 0
#     maxUnavailable: 25%
#   type: RollingUpdate

volumes: []

debug: false

# service:
#   type: NodePort
#   port: 80

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []
# tolerations:
#  - effect: NoSchedule
#    key: plex-only
#    operator: Equal
#    value: "true"
affinity: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

### Additions for minio mounts

terminationGracePeriodSeconds: 10

podSecurityContext: {}

securityContext: {}

updateStrategy:
  ## @param updateStrategy.type Deployment deployment update strategy
  type: RollingUpdate
  ## @param updateStrategy.rollingUpdate Deployment deployment rolling update configuration parameters
  rollingUpdate: {}

istio:
  enabled: false
