apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vault.fullname" . }}-config
  labels:
{{ include "vault.standard" . | indent 4 }}
data:
  config.json: |
    {{ .Values.vault.config | toJson }}
