{{- $root := . }}
{{- range $index, $service := .Values.services }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $service.name }}
  labels:
{{ include "istio-service.labels" $root | indent 4 }}
spec:
  hosts:
{{ toYaml $service.hosts | indent 4 }}
  gateways:
    - {{ $service.name }}-gateway
  http:
{{- if $service.routes }}
{{ toYaml $service.routes | indent 4 }}
{{- else }}
    - route:
        - destination:
            host: {{$service.hosts | first}}
            port:
              number: {{ $service.port }}
          weight: 100
{{- end }}
{{- end }}