apiVersion: v1
name: consul
version: 0.1.4
appVersion: 1.3.1
description: Install and configure Consul on Kubernetes.
home: https://www.consul.io
sources:
  - https://github.com/hashicorp/consul
  - https://github.com/hashicorp/consul-helm
  - https://github.com/hashicorp/consul-k8s
maintainers:
  - name: Holden Omans
    email: holden.omans@gmail.com
