# Service for Consul DNS.
{{- if (or (and (ne (.Values.dns.enabled | toString) "-") .Values.dns.enabled) (and (eq (.Values.dns.enabled | toString) "-") .Values.global.enabled)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "consul.fullname" . }}-dns
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "consul.standard" . | indent 4 }}
spec:
  clusterIP: {{ .Values.dns.clusterIP }}
  ports:
    - name: dns-tcp
      port: 53
      protocol: "TCP"
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: "UDP"
      targetPort: dns-udp
  selector:
    app: {{ template "consul.name" . }}
    release: "{{ .Release.Name }}"
    component: server
    hasDNS: "true"
{{- end }}
