apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
{{- if .Values.labels }}
  {{- toYaml .Values.labels | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        kalinon.com/group: {{ include "app.name" . }}
        kalinon.com/app: {{ .Release.Name }}
{{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 8 }}
{{- end }}
    spec:
    {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
    {{- end }}
    {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
    {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "app.serviceAccountName" . }}
      securityContext:
{{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
{{ toYaml .Values.initContainers | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true
          stdin: true
          {{- if .Values.workingDir }}
          workingDir: {{ .Values.workingDir }}
          {{- end }}

          {{- if .Values.debug }}
          command: ["/bin/sh", "-c"]
          args: ["while true; do sleep 30; echo 'debug mode'; done"]
          {{- else }}
          {{- if .Values.command }}
          command: {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args: {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with .Values.envs }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.debug }}
          {{- else }}
          {{- if .Values.startupProbe }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.volumes }}
          volumeMounts:
          {{- range $index, $volume := .Values.volumes }}
          {{- with $volume }}
            {{- if hasKey . "configMap" }}
            - name: {{ .configMap }}
              mountPath: {{ .path }}
              {{- if hasKey . "subPath" }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- else if hasKey . "secret" }}
            - mountPath: {{ .path }}
              {{- if hasKey . "name" }}
              name: {{ .name }}
              {{- else }}
              name: {{ .secret }}
              {{- end }}
              {{- if hasKey . "subPath" }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- else }}
              {{- if hasKey . "mounts" }}
              {{- $name := .name }}
              {{- range $i, $mount := .mounts }}
            - name: {{ $name }}
              mountPath: {{ $mount.mountPath }}
              subPath: {{ $mount.subPath }}
              {{- end }}
              {{- else }}
            - name: {{ .name }}
              mountPath: {{ .path }}
              {{- if hasKey . "subPath" }}
              subPath: {{ .subPath }}
              {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- if .Values.sidecars }}
{{ toYaml .Values.sidecars | indent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- if .Values.volumes }}
  {{- $root := . }}
      volumes:
{{- range $index, $volume := .Values.volumes }}
{{- with $volume }}
    {{- if hasKey . "configMap" }}
      - configMap:
          defaultMode: {{ .defaultMode | default 292 }}
          name: {{ .configMap }}
          optional: false
          {{- if hasKey . "items" }}
          items:
            {{- toYaml .items | nindent 14 }}
          {{- end }}
        {{- if hasKey . "name" }}
        name: {{ .name }}
        {{- else }}
        name: {{ .configMap }}
        {{- end }}
    {{- else if hasKey . "secret" }}
      - secret:
          defaultMode: {{ .defaultMode | default 292 }}
          secretName: {{ .secret }}
          optional: false
          {{- if hasKey . "items" }}
          items:
            {{- toYaml .items | nindent 12 }}
          {{- end }}
        {{- if hasKey . "name" }}
        name: {{ .name }}
        {{- else }}
        name: {{ .secret }}
        {{- end }}
    {{- else if hasKey . "shared" }}
      - name: {{ .name }}
        emptyDir: {}
    {{- else if hasKey . "persistentVolumeClaim" }}
      - name: {{ .name }}
        persistentVolumeClaim:
          {{- toYaml .persistentVolumeClaim | nindent 12 }}
    {{- else }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ $root.Release.Name }}-{{ .name }}-pvc
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
