{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $portName := "http" -}}
{{- $k8sver := .Capabilities.KubeVersion.GitVersion -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "app.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    {{- if hasKey . "portName" }}
      {{- $portName = .portName -}}
    {{- end }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            {{- if semverCompare ">=1.19-0" $k8sver }}
            pathType: ImplementationSpecific
            backend:
              {{- if hasKey . "service" }}
              service:
                {{- toYaml .service | nindent 16 }}
              {{- else }}
              service:
                name: {{ $fullName }}
                port:
                  name: {{ $portName }}
              {{- end }}
            {{- else }}
            backend:
              serviceName: {{ default $fullName .serviceName }}
              servicePort: {{ default $portName .servicePort }}
            {{- end }}
        {{- end }}
  {{- $portName = "http" -}}
  {{- end }}
{{- end }}
