{{- if .Values.istio.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $portName := "http" -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-cert
  namespace: {{ .Values.istio.gateway.namespace }}
  labels:
{{ include "app.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  dnsNames:
  {{- range .Values.istio.hosts }}
    - {{ . | quote }}
  {{- end }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: {{ $fullName }}-tls
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $fullName }}-gateway
  labels:
{{ include "app.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- toYaml .Values.istio.gateway.selector | nindent 4 }}
  servers:
    - hosts:
      {{- range .Values.istio.hosts }}
        - {{ . | quote }}
      {{- end }}
      name: https
      port:
        name: https-443
        number: 443
        protocol: HTTPS
      tls:
        credentialName: {{ $fullName }}-tls
        mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  hosts:
    {{- range .Values.istio.hosts }}
      - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ $fullName }}-gateway
  http:
    - route:
        - destination:
            host: {{$fullName}}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{default $svcPort 80}}
          weight: 100
{{- end }}
