{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.serviceAccountName" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
{{- if .Values.labels }}
  {{- toYaml .Values.labels | nindent 4 }}
{{- end }}
{{- end -}}
