apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
{{ include "vault.standard" . | indent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "vault.name" . }}
      release: {{ .Release.Name }}
      component: server
